# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Cacus_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  Cacus_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  Cacus_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Cacus Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Cacus:
ifneq (,$(Cacus_config))
	@echo "==== Building Cacus ($(Cacus_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(Cacus_config)
endif

Sandbox: Cacus
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C examples/Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean
	@${MAKE} --no-print-directory -C examples/Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Cacus"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"